name: Release Creation

on:
  push:
    branches:
      - prod
      tags:
        - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ github.ref }}
          title: Release ${{ github.ref }}
          prerelease: false
