name: Release Creation

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Branch
        id: get_branch
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw/origin\/}
          echo $branch
          echo "BRANCH=$branch" >> $GITHUB_ENV
          echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo $GITHUB_ENV

      - name: Print something
        run: |
          echo $branch
          echo $GITHUB_ENV
          echo $env.BRANCH

      - name: Create Release
        if: $env.BRANCH == 'prod'
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ github.ref }}
          title: Release ${{ env.TAG }}
          prerelease: false
