name: Create Tag

#on:
#  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: butlerlogic/action-autotag@stable
      id: tag_version
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        strategy: docker
        tag_prefix: "v"

    - name: print tag
      run: |
        echo "${{ steps.tag_version.outputs.tagname }}"
