name: Create Tag

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#      - uses: butlerlogic/action-autotag@stable
#        id: tag_version
#        with:
#          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
#          strategy: docker
#          tag_prefix: "v"
#
#      - name: Print tag
#        run: |
#          echo "${{ steps.tag_version.outputs.tagname }}"

      - name: Build changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          fromTag: "v1.0.1"
          toTag: "v1.0.70"

      - name: Print Change Catalog
        run: |
          echo "${{ steps.build_changelog.outputs.owner }}"
          echo "${{ steps.build_changelog.outputs.repo }}"
          echo "${{ steps.build_changelog.outputs.fromTag }}"
          echo "${{ steps.build_changelog.outputs.toTag }}"
          echo "${{ steps.build_changelog.outputs.failed }}"
          echo ${{steps.build_changelog.outputs.changelog}}