# Reference: https://github.com/marketplace/actions/slack-notify

# Github action to push Slack notifications
name: Slack Notification

on: push

jobs:
  slackNotification:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout latest code
      uses: actions/checkout@v2

    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: 'Post Content :rocket:'
        MSG_MINIMAL: true
