name: Slack Notification

on: push

jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_MESSAGE: 'Post Content :rocket:'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
#    - name: Notify slack
#      env:
#        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
#      uses: pullreminders/slack-action@master
#      with:
#        args: '{\"channel\":\"D02S1BT4GS3\",\"text\":\"Hello world\"}'
