name: PR Action

on: [push]

jobs:
    PR Check:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.7

            - name: Validate version
              run: python --version

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements/base.txt
                  pip install -r requirements/ci.txt
                  pip install awscli

            - name: Run Deployment script
              run: sh ./scripts/deploy-aws.sh
